### ISSUE TITLE
Q: dynamic paths

### ISSUE THREAD

**Issue by basz** [basz/shoelace-ember#4]
these are hardcoded that might interfere with hoisting

https://github.com/basz/shoelace-ember/blob/main/%40shoelace-style/ember/rollup.config.mjs#L69

how to avoid?

**Comment by NullVoxPopuli** [comment]
you shouldn't need to copy over the CSS, your addon can import those files directly (because you specified a dependency), or README instructions can be added for the consuming app to do it.

I'd delete all of this: https://github.com/basz/shoelace-ember/blob/main/%40shoelace-style/ember/rollup.config.mjs#L64-L71
